name: CD Production
on:
  workflow_run:
    workflows: [ Continuous Integration ]
    types: [ completed ]

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build Android application
        run: ./gradlew clean build
      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: apks
          path: app/build/**/*.apk